# Generated by Django 5.2.1 on 2025-10-15 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_reassort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='caisse.vente'),
        ),
    ]
