# Generated by Django 5.2.1 on 2025-10-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_alter_paiement_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remise',
            name='appliquee_a',
        ),
        migrations.AddField(
            model_name='remise',
            name='appliquee_a_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='caisse.produit'),
        ),
        migrations.AddField(
            model_name='remise',
            name='appliquee_a_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caisse.vente'),
        ),
        migrations.AlterField(
            model_name='remise',
            name='type',
            field=models.CharField(choices=[('pourcentage', 'Pourcentage'), ('fixe', 'Valeur fixe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
