# Generated by Django 5.2.1 on 2025-10-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_remove_remise_appliquee_a_remise_appliquee_a_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remise',
            name='appliquee_a_produit',
        ),
        migrations.RemoveField(
            model_name='remise',
            name='appliquee_a_vente',
        ),
        migrations.AddField(
            model_name='remise',
            name='appliquee_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='caisse.vente'),
        ),
        migrations.AlterField(
            model_name='remise',
            name='type',
            field=models.CharField(choices=[('pourcentage', 'Pourcentage'), ('valeur', 'Valeur fixe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
